# List available targets
default:
    @just --list

# Full install: link dotfiles and install packages
install: brew-install link install-runtimes

# Stow all packages
link:
    stow zsh git starship

# Restow all packages (use to apply structural changes without conflicts)
relink:
    stow --restow zsh git starship

# Unstow all packages
unlink:
    stow -D zsh git starship

# Install core CLI tools
brew-install:
    brew bundle --file=Brewfile

# Install optional GUI apps and App Store apps (not run by default)
install-apps:
    brew bundle --file=Brewfile.optional
    @echo "Manually install the following apps from the App Store:"
    @echo "    - Xcode"
    @echo "    - Slack for Desktop"
    @echo "    - Magnet"

    @echo ""
    @echo "Manually download and install:"
    @echo "    - IntelliJ @ https://www.jetbrains.com/idea/download "
    @echo "    - Discord @ https://discord.com/download " 

# Install all language runtimes
install-runtimes: install-sdkman install-nvm install-rbenv

install-sdkman:
    bash install/sdkman.sh

install-nvm:
    bash install/nvm.sh

install-rbenv:
    bash install/rbenv.sh

# Upgrade everything
update:
    brew update && brew upgrade
    brew bundle --cleanup --file=Brewfile
    -sdk selfupdate
    -sdk update
    -nvm install --lts --reinstall-packages-from=current
    -rbenv update || true

# Apply macOS system defaults (run explicitly, not part of just install)
macos:
    bash macos/defaults.sh

# Check what brew bundle would change
brew-check:
    brew bundle check --file=Brewfile
    brew bundle check --file=Brewfile.optional

# Run all machine-local setup steps (zsh + git). Run this on each new machine after `just install`
setup: setup-zsh setup-git

# Generate SSH keys and verify GitHub connectivity
setup-ssh-keys:
    bash install/configure_ssh.sh

# Build or update ~/.ssh/config interactively
setup-ssh-config:
    bash install/configure_ssh_config.sh

# Full SSH setup: key generation + config builder (run on new machines)
setup-ssh: setup-ssh-keys setup-ssh-config

# Set up machine-local shell environment (writes to ~/.zshrc.local)
setup-zsh:
    #!/usr/bin/env bash
    set -e
    local_file="$HOME/.zshrc.local"

    if [[ -f "$local_file" ]]; then
      echo "~/.zshrc.local already exists. Current contents:"
      echo "---"
      cat "$local_file"
      echo "---"
      read -rp "Overwrite it? [y/N] " confirm
      [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
    fi

    read -rp "Path to your dev directory [default: $HOME/dev]: " dev_path
    dev_path="${dev_path:-$HOME/dev}"

    read -rp "Path to CONFLUENT_HOME (leave blank to skip): " confluent_path

    {
      echo "# Machine-local shell environment — not committed to repo"
      echo "# Generated by: just setup-zsh"
      echo ""
      echo "export DEV=\"$dev_path\""
      if [[ -n "$confluent_path" ]]; then
        echo "export CONFLUENT_HOME=\"$confluent_path\""
        echo "export PATH=\"\$PATH:\$CONFLUENT_HOME/bin\""
      fi
    } > "$local_file"

    echo ""
    echo "Written to $local_file"

# Set up machine-local git identity (writes to ~/.gitconfig.local)
setup-git:
    #!/usr/bin/env bash
    set -e
    local_file="$HOME/.gitconfig.local"

    if [[ -f "$local_file" ]]; then
      echo "~/.gitconfig.local already exists. Current contents:"
      echo "---"
      cat "$local_file"
      echo "---"
      read -rp "Overwrite it? [y/N] " confirm
      [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
    fi

    read -rp "Git name [default: Derek Eskens]: " git_name
    git_name="${git_name:-Derek Eskens}"

    read -rp "Git email [default: snekse@gmail.com]: " git_email
    git_email="${git_email:-snekse@gmail.com}"

    {
      echo "# Machine-local git identity — not committed to repo"
      echo "# Generated by: just setup-git"
      echo ""
      echo "[user]"
      echo "  name = $git_name"
      echo "  email = $git_email"
    } > "$local_file"

    echo ""
    echo "Written to $local_file"
