# List available targets
default:
    @just --list

# Full install: link dotfiles and install packages
install: brew-install link

# Stow all packages
link:
    stow zsh git starship

# Unstow all packages
unlink:
    stow -D zsh git starship

# Install core CLI tools
brew-install:
    brew bundle --file=Brewfile

# Install optional GUI apps and App Store apps (not run by default)
install-apps:
    brew bundle --file=Brewfile.optional

# Upgrade everything
update:
    brew update && brew upgrade
    brew bundle --cleanup --file=Brewfile

# Check what brew bundle would change
brew-check:
    brew bundle check --file=Brewfile
    brew bundle check --file=Brewfile.optional

# Set up machine-local environment variables (writes to ~/.zshrc.local)
# Run this on each new machine after `just install`
setup:
    #!/usr/bin/env bash
    set -e
    local_file="$HOME/.zshrc.local"

    if [[ -f "$local_file" ]]; then
      echo "~/.zshrc.local already exists. Current contents:"
      echo "---"
      cat "$local_file"
      echo "---"
      read -rp "Overwrite it? [y/N] " confirm
      [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
    fi

    read -rp "Path to your dev directory [default: $HOME/dev]: " dev_path
    dev_path="${dev_path:-$HOME/dev}"

    read -rp "Path to CONFLUENT_HOME (leave blank to skip): " confluent_path

    {
      echo "# Machine-local environment — not committed to repo"
      echo "# Generated by: just setup"
      echo ""
      echo "export DEV=\"$dev_path\""
      if [[ -n "$confluent_path" ]]; then
        echo "export CONFLUENT_HOME=\"$confluent_path\""
        echo "export PATH=\"\$PATH:\$CONFLUENT_HOME/bin\""
      fi
    } > "$local_file"

    echo ""
    echo "Written to $local_file"
